/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.shoe.http_scrapping;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
